# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "merill.net"
email: "merill@merill.net"
subtitle: "my utmost for his highest, my best for his glory"
name: "Merill Fernando"
description: "Ramblings of an Ex-Microsoft MVP, Cloud Architect, Microsoft 365 DevOps Lead"
repository: "merill/merill.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://merill.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: merill
github_username:  merill
search: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default," "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true 


# Site owner
author:
  name: "Merill Fernando"
  uri: &uri "/about/"
  url: *uri
  bio: "Ex-Microsoft MVP, Cloud Architect, Microsoft 365 DevOps Lead"
  location: Melbourne, Australia
  avatar: "/assets/images/merill-profile.png"
  og_image: "/assets/images/merill-profile.png"
  twitter: "merill"
  github: "merill"
  linkedin: "merill"
  email: merill@merill.net

twitter:
  username: "merill"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/merill"
    - "https://www.linkedin.com/in/merill"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/merill"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/merill"
    - label: "Linked In"
      icon: "fab fa-fw fa-linked-in"
      url: "https://linkedin.com/in/merill"

# Outputting
permalink: /:year/:month/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
comments:
  provider               : disqus # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : merill # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-33485614-1
    anonymize_ip         : # true, false (default)

include: ["_pages"]

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
